Adds Web Servers samples
paketo-buildpacks/samples pull request #329
Opened 2022-05-10 19:22 UTC by ForestEckhardt

Resolves #322

2022-05-10 19:24 UTC, ForestEckhardt commented
Needed for RFC 0047 https://github.com/paketo-buildpacks/rfcs/issues/193

2022-05-10 19:25 UTC, ForestEckhardt commented
Test is failing waiting for addition of Web Server buildpack to the full builder

2022-05-12 18:33 UTC, TisVictress commented on web-servers/no-config-file-sample/README.md
> +This directory hass all of the components to for a sample of a zero
On line 2, `has` is misspelled and you don't need `to` after components.

2022-05-12 18:36 UTC, TisVictress requested changes
This LGTM :-) Just some misspellings but otherwise I approve.

2022-05-12 18:39 UTC, TisVictress approved these changes
LOL you made the changes already.

2022-05-12 19:10 UTC, thitch97 approved these changes

2022-05-12 19:14 UTC, merged