Adds Nodejs sample app that does not use a package manager
paketo-buildpacks/samples pull request #72
Opened 2021-02-16 16:37 UTC by ForestEckhardt

- Adds sample app for support Nodejs workflow that does not use a
package manager
- Adds sample to tests

Resolves #11 

## Checklist
* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have added an integration test, if necessary.

2021-02-17 18:12 UTC, arjun024 requested changes

2021-02-17 18:12 UTC, arjun024 commented on tests/node_test.go
> +			context("app uses npm", func() {
```suggestion
			context("no package manager", func() {
```

2021-02-18 15:22 UTC, arjun024 approved these changes

2021-02-18 15:24 UTC, arjun024 commented
@paketo-buildpacks/content-maintainers Approved. I'm not authorized to merge

2021-02-18 16:00 UTC, kvedurmu approved these changes

2021-02-18 16:00 UTC, merged